Repository teamcrusher/threewide, pull requests merged in 2022-11, with the labels that each got.

#38 Design prototypes
  Design documentation/README.md
  Design documentation/ThreeWide_Lo-fi Prototype.pdf
Labels: Support work

#39 Added tetris flow diagram
  Diagrams/Tetris flow.md
Labels: Support work

#37 Activity 3 readmes
  Design documentation/README.md
  README.md
Labels: documentation, Support work

#41 fix render on flow
  Diagrams/Tetris flow.md
Labels: bug, documentation, Support work

#46 update readme for act 3
  Design documentation/README.md
Labels: documentation, Support work

#47 lost the links, fixed
  Design documentation/README.md
Labels: duplicate

#49 add hifi link
  README.md
Labels: Support work

#45 add user questionaire
  Design documentation/User-questionaire.md
Labels: documentation, Support work

#44 30 sequence diagram
  Diagrams/Sequence_Diagram.md
Labels: documentation, Support work

#43 commit updated state diagram
  Diagrams/State-diagram.md
Labels: documentation, Support work

#42 init UJD
  Diagrams/User Journey Diagram.md
Labels: documentation, Support work

#40 init ERD
  Diagrams/Data-model.md
Labels: documentation, Support work

#50 Activity 3 readmes
  Design documentation/README.md
  README.md
Labels: Support work

#51 activity 3 closeout
  Design documentation/Diagrams/Data-model.md
  Design documentation/Diagrams/MVC-architecture-overview.md
  Design documentation/Diagrams/Sequence-Diagram.md
  Design documentation/Diagrams/State-diagram.md
  Design documentation/Diagrams/Tetris-flow.md
  Design documentation/Diagrams/User-journey-diagram.md
  Design documentation/Prototypes.md
  Design documentation/User-questionaire.md
Labels: documentation, Support work

#62 Created t3 app
  threewide/.env-example
  threewide/.eslintrc.json
  threewide/.gitignore
  threewide/README.md
  threewide/next-env.d.ts
  threewide/next.config.mjs
  threewide/package-lock.json
  threewide/package.json
  threewide/postcss.config.cjs
  threewide/prettier.config.cjs
  threewide/public/BoardTiles/DefaultTile.png
  threewide/public/BoardTiles/ITile.png
  threewide/public/BoardTiles/JTile.png
  threewide/public/BoardTiles/LTile.png
  threewide/public/BoardTiles/OTile.png
  threewide/public/BoardTiles/STile.png
  threewide/public/BoardTiles/ShadowPiece.png
  threewide/public/BoardTiles/TTile.png
  threewide/public/BoardTiles/ZTile.png
  threewide/public/BoardTiles/index.js
  threewide/public/favicon.ico
  threewide/src/components/Board.tsx
  threewide/src/components/BoardTile.tsx
  threewide/src/components/Game.tsx
  threewide/src/components/KeyListener.tsx
  threewide/src/components/Piece.tsx
  threewide/src/components/PieceQueue.tsx
  threewide/src/components/Tetris.tsx
  threewide/src/env/client.mjs
  threewide/src/env/schema.mjs
  threewide/src/env/server.mjs
  threewide/src/models/game_description.model.ts
  threewide/src/models/stategy.model.ts
  threewide/src/models/user.model.ts
  threewide/src/pages/_app.tsx
  threewide/src/pages/api/auth/[...nextauth].ts
  threewide/src/pages/api/restricted.ts
  threewide/src/pages/api/trpc/[trpc].ts
  threewide/src/pages/index.tsx
  threewide/src/pages/login.tsx
  threewide/src/pages/strategy.tsx
  threewide/src/server/common/get-server-auth-session.ts
  threewide/src/server/trpc/context.ts
  threewide/src/server/trpc/router/_app.ts
  threewide/src/server/trpc/router/auth.ts
  threewide/src/server/trpc/router/example.ts
  threewide/src/server/trpc/router/gameDescription.ts
  threewide/src/server/trpc/router/strategy.ts
  threewide/src/server/trpc/trpc.ts
  threewide/src/styles/globals.css
  threewide/src/types/next-auth.d.ts
  threewide/src/types/tetris.ts
  threewide/src/utils/mongoose.ts
  threewide/src/utils/tetris/PieceKickTables.ts
  threewide/src/utils/tetris/PieceRotations.ts
  threewide/src/utils/tetris/PieceSizes.ts
  threewide/src/utils/trpc.ts
  threewide/tailwind.config.cjs
  threewide/testgamedatatoadd.json
  threewide/tsconfig.json
Labels: enhancement

#87 Made queue generation occur only on the client
  threewide/src/components/Piece.tsx
  threewide/src/components/Tetris.tsx
Labels: enhancement

#86 Add persistance to user game data
  threewide/src/models/game_description.model.ts
  threewide/src/models/user.model.ts
  threewide/src/models/user_game_result.model.ts
  threewide/src/pages/api/auth/[...nextauth].ts
  threewide/src/pages/strategy.tsx
  threewide/src/server/trpc/router/_app.ts
  threewide/src/server/trpc/router/gameDescription.ts
  threewide/src/server/trpc/router/userGameResult.ts
Labels: enhancement

#94 Implement strategy page design
  threewide/next.config.mjs
  threewide/package-lock.json
  threewide/package.json
  threewide/public/favicon.ico
  threewide/public/logo.svg
  threewide/src/components/Board.tsx
  threewide/src/components/EndGame.tsx
  threewide/src/components/Game.tsx
  threewide/src/components/Goal.tsx
  threewide/src/components/Header.tsx
  threewide/src/components/KeyListener.tsx
  threewide/src/components/Piece.tsx
  threewide/src/components/PieceQueue.tsx
  threewide/src/components/Settings.tsx
  threewide/src/components/Tetris.tsx
  threewide/src/models/game_description.model.ts
  threewide/src/models/user.model.ts
  threewide/src/pages/api/auth/[...nextauth].ts
  threewide/src/pages/index.tsx
  threewide/src/pages/login.tsx
  threewide/src/pages/strategy.tsx
  threewide/src/server/trpc/router/_app.ts
  threewide/src/server/trpc/router/gameDescription.ts
  threewide/src/server/trpc/router/user.ts
  threewide/src/styles/globals.css
  threewide/src/types/tetris.ts
  threewide/src/utils/tetris/PieceKickTables.ts
  threewide/testgamedatatoadd.json
Labels: bug, enhancement

#98 Project Presentation Files
  Team Crusher_Final Presentation.pdf
Labels: documentation
